In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
print('Versão numpy', np.__version__)

Versão numpy 1.18.5


In [3]:
#Array a partir de uma lista 
quantidade = [3, 6, 12, 25, 40]
custo = [110, 150, 480, 200, 60]

In [4]:
quantidade


[3, 6, 12, 25, 40]

In [5]:
#Criar Array 1 - Quantidade
Quantidade_array = np.array(quantidade)
print(Quantidade_array)

[ 3  6 12 25 40]


In [6]:
Quantidade_array

array([ 3,  6, 12, 25, 40])

In [7]:
#Criar Array 2 - Custo
Custo_array = np.array(custo)
print(Custo_array)

[110 150 480 200  60]


In [8]:
Custo_array

array([110, 150, 480, 200,  60])

In [10]:
#Calcular valor de estoque 
Estoque = Quantidade_array * Custo_array
print('O total de estoque é:', Estoque)

O total de estoque é: [ 330  900 5760 5000 2400]


In [11]:
#Criação do array custo e vendas
vendas = [200, 100, 40, 500]
custo_venda = [123, 145, 334, 480]

In [12]:
#Criar array dentro do numpy
CustoVenda_array = np.array(custo_venda)
Venda_array = np.array(vendas)

In [14]:
#Verificar lucro
Lucro = CustoVenda_array - Venda_array
print('O Lucro é:',Lucro)

O Lucro é: [-77  45 294 -20]


In [17]:
#função arange(), que seria o for de uma linha
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

In [18]:
for_numpy = np.arange(2, 20, 2)

In [19]:
for_numpy

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [20]:
print('O for do numpy de uma linha é:',for_numpy)

O for do numpy de uma linha é: [ 2  4  6  8 10 12 14 16 18]


In [23]:
for_float = np.arange(2.5, 50, 2, dtype = float)
for_float

array([ 2.5,  4.5,  6.5,  8.5, 10.5, 12.5, 14.5, 16.5, 18.5, 20.5, 22.5,
       24.5, 26.5, 28.5, 30.5, 32.5, 34.5, 36.5, 38.5, 40.5, 42.5, 44.5,
       46.5, 48.5])